// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef data_glove_win_fl_h
#define data_glove_win_fl_h
# include "data_glove_win_events.h"
#include <fltk/Window.h>
#include <fltk/TiledGroup.h>
#include <fltk/Group.h>
#include <fltk/MenuBar.h>
#include <fltk/Item.h>
#include <fltk/ItemGroup.h>
#include <fltk/TabGroup.h>
#include <fltk/ValueOutput.h>
#include <fltk/Input.h>
#include <fltk/Button.h>
#include <fltk/LightButton.h>

class DataGloveFluid  {
public:
  virtual void event ( GloveEvent e )=0;
  DataGloveFluid();
  fltk::Window *ui_window;
      fltk::Group *ui_main_group;
private:
          inline void cb_X_i(fltk::Item*, void*);
          static void cb_X(fltk::Item*, void*);
            inline void cb_set_i(fltk::Item*, void*);
            static void cb_set(fltk::Item*, void*);
            inline void cb_set1_i(fltk::Item*, void*);
            static void cb_set1(fltk::Item*, void*);
            inline void cb_set2_i(fltk::Item*, void*);
            static void cb_set2(fltk::Item*, void*);
public:
          fltk::TabGroup *ui_main_tab;
              fltk::ValueOutput *data[18];
              fltk::ValueOutput *data_min[18];
              fltk::Input *ui_glove_config;
private:
              inline void cb_load_i(fltk::Button*, void*);
              static void cb_load(fltk::Button*, void*);
              inline void cb_save_i(fltk::Button*, void*);
              static void cb_save(fltk::Button*, void*);
              inline void cb_pose_i(fltk::Button*, void*);
              static void cb_pose(fltk::Button*, void*);
              inline void cb_pose1_i(fltk::Button*, void*);
              static void cb_pose1(fltk::Button*, void*);
public:
              fltk::ValueOutput *ui_interp_output;
private:
                inline void cb_hand_i(fltk::Button*, void*);
                static void cb_hand(fltk::Button*, void*);
                inline void cb_hand1_i(fltk::Button*, void*);
                static void cb_hand1(fltk::Button*, void*);
                inline void cb_thumb_i(fltk::Button*, void*);
                static void cb_thumb(fltk::Button*, void*);
public:
        fltk::LightButton *ui_glove_active;
};
#endif
