// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef game_fluid_h
#define game_fluid_h
# include "game_events.h"
# include "game_viewer.h"
#include <fltk/Window.h>
#include <fltk/Group.h>
#include <fltk/ValueSlider.h>
#include <fltk/Button.h>

class GameWindowFluid  {
public:
  virtual void event ( GameWindowEvent e )=0;
  GameWindowFluid();
  fltk::Window *ui_window;
      fltk::ValueSlider *ui_jump_distance;
private:
      inline void cb_ui_jump_distance_i(fltk::ValueSlider*, void*);
      static void cb_ui_jump_distance(fltk::ValueSlider*, void*);
public:
      fltk::ValueSlider *ui_jump_height;
private:
      inline void cb_ui_jump_height_i(fltk::ValueSlider*, void*);
      static void cb_ui_jump_height(fltk::ValueSlider*, void*);
      inline void cb_Jump_i(fltk::Button*, void*);
      static void cb_Jump(fltk::Button*, void*);
      inline void cb_Reset_i(fltk::Button*, void*);
      static void cb_Reset(fltk::Button*, void*);
      inline void cb_Quit_i(fltk::Button*, void*);
      static void cb_Quit(fltk::Button*, void*);
};
#endif
